AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an ec2 instance.
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key Pair Name
    Type: String
    Default: Rabi
  UserName:
    Description: User Name
    Type: String
    Default: ''
  InstanceType:
    Description: Instance Type
    Type: String
    Default: t2.micro
  InstanceImageId:
    Description: Image ID
    Type: String
    Default: 'ami-07d0cf3af28718ef8'
  VpcId:
    Description: Vpc ID
    Type: AWS::EC2::VPC::Id
    Default: vpc-b7cadbcf
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: SubnetID with validation and default value
    Default: subnet-c6c1e6a2

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - 
          Description: Allowed from anywhere
          IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
      Tags:
        -
          Key: username
          Value: !Ref UserName

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref InstanceImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        -
          !GetAtt InstanceSecurityGroup.GroupId
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetID
      # AvailabilityZone: us-east-1a
      Tags:
        -
          Key: username
          Value: !Ref UserName

Outputs:
  InstancePublicIP:
    Description: The Public IP Address of EC2 Instance
    Value: !GetAtt EC2Instance.PublicIp
  InstancePrivateIP:
    Description: The Private IP Address of EC2 Instance
    Value: !GetAtt EC2Instance.PrivateIp
  